addSbtPlugin("io.verizon.build" % "sbt-rig" % "5.0.39")
addSbtPlugin("org.lyranthe.sbt" % "partial-unification" % "1.1.2")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.6.0")
addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat" % "0.1.8")